### ISSUE TITLE
有事都提 issues 近期 TODO list

### ISSUE THREAD

**Issue by imzyf** [network-center/network-center.github.io.hexo#2]
1. 建设主站
2. 拉拉熟人
3. research github
4. 定一个 logo

@tyl569 @freetureAI @wave-gbt

**Comment by imzyf** [comment]
你们可以都 watch 下项目，会及时收到通知

**Comment by imzyf** [comment]
你们都是 owner 了

**Comment by freetureAI** [comment]
这个站的主要目的是什么呀？

**Comment by imzyf** [comment]
@freetureAI 
那个项目 issues 说了：

准备打着社团的旗号，对外联系一波学长、盆友们，对校内带带学弟学妹。

交流总结，多认识认识人，盆友之间多交流技术，一起进步

**Comment by imzyf** [comment]
@freetureAI 也是感受下远程协同这种模式，严格控制项目内容质量

**Comment by wave-gbt** [comment]
fork 了一个简历仓库，帆哥觉得不合适就去掉啊 ：）

**Comment by imzyf** [comment]
@wave-gbt 多多参与

**Comment by tyl569** [comment]
主站内容什么要求？ 技术博客分享？ 对内容实用性有没有要求？

**Comment by tyl569** [comment]
每周每人至少贡献一篇？ 等等

**Comment by imzyf** [comment]
@tyl569 肯定是技术相关的，但不限于。几个基本原则（还可以再讨论）：

**• 这里绝对不会全文转载任何文章，而只会以链接方式分享** 
**• 这里尊重原创** 
**• 这里反对中文互联网上的无信息量习惯如“顶”，“沙发”，“前排”，“留名”，“路过”，“不明觉厉”** 

这个 v2ex 的规定我们可以参考 https://www.v2ex.com/about


> 每周每人至少贡献一篇

前期还可以，后面可能有点苛刻

**Comment by tyl569** [comment]
#### 1. 关于网站信息：主要写网站创建的目的和愿景吧
#### 2. 前期可以主要是一些技术分类（可能不全或者冗余），后面可以拓展其他目录：
- 后端
  - Linux
  - Nginx
  - Apache
  - MySQL
  - Java
  - PHP
  - NodeJs
  - C#
  - Python
- 前端
  - CSS
  - JS
  - HTML
- 测试
- Android
- iOS
#### 3. 目录结构可以参考[美团点评技术团队](https://tech.meituan.com) ，比较简单
#### 4. 项目编写规范可以参考[Google StyleGuide](https://github.com/google/styleguide/blob/gh-pages/docguide/style.md)
#### 5. 参与项目的流程
- fork这个项目
- 提交Pull Requests
- 在一段时间后，如果对项目还有热情可以直接给你开放提交权限

@imzyf @wave-gbt @freetureAI

**Comment by wave-gbt** [comment]
关于如何参与项目的流程可以具体介绍下吗？比如：
0. 把 network-center.github.io.hexo clone 到个人本地之后，需要哪些操作？
1. 主站的推送（https/ssh）
2. markdown 源码的备份库的提交
3. 如何提交才能不把 github 上的 README.md 文件丢失
...

**Comment by tyl569** [comment]
OK，我整理详细一些，然后加到wiki里面吧。如果内容有不合适的地方，大家提出来

**Comment by imzyf** [comment]
最近工作的事情比较多，今天我一定将 hexo 的网站配置好

**Comment by wave-gbt** [comment]
一个小建议： 帆哥，让刘菲设计一个logo啊

**Comment by imzyf** [comment]
@wave-gbt 想到了 设计中

**Comment by imzyf** [comment]
写入 wiki，每个以后每个 issues 只处理一个事情，还有问题单独提交 issues
