### ISSUE TITLE
logo 样式 投票

### ISSUE THREAD

**Issue by imzyf** [network-center/network-center.github.io.hexo#3]
![2017-08-31 1](https://user-images.githubusercontent.com/9289792/29923491-4bb62886-8e8c-11e7-9f8c-424528d564a5.png)
![2017-08-31 2](https://user-images.githubusercontent.com/9289792/29923492-4bb6762e-8e8c-11e7-98c9-04550ab63e1a.png)
![2017-08-31](https://user-images.githubusercontent.com/9289792/29923493-4be74484-8e8c-11e7-9b2e-ce7e4a51d63f.png)

thanks huihui

**Comment by wave-gbt** [comment]
I like the third.

**Comment by tyl569** [comment]
我觉得都还OK

**Comment by imzyf** [comment]
![network-center](https://user-images.githubusercontent.com/9289792/29961538-89c2375e-8f32-11e7-843c-7d5851a9590c.png)

终稿
