### ISSUE TITLE
发布了新文章 keep going

### ISSUE THREAD

**Issue by imzyf** [network-center/network-center.github.io.hexo#7]
https://network-center.github.io/2017/09/15/keep-going/

@tyl569 @wave-gbt @freetureAI @zhaosiqi111

**Comment by imzyf** [comment]
大家来 聊聊最近在做什么 方面东西呢？

我在研究 Swift 准备 iOS 的开发，《iOS Apprentice》这本书很不错，今天看完了第二个项目

https://github.com/imzyf/ios-apprentice-checklists

**Comment by imzyf** [comment]
《Complete Code》 代码大全，神书

**Comment by wave-gbt** [comment]
走过你来时的路~

**Comment by tyl569** [comment]
最近一直在看PHP的一些内核源码。数据结构比较欠缺，进度slow。
