### ISSUE TITLE
页面生成

### ISSUE THREAD

**Issue by tyl569** [network-center/network-center.github.io.hexo#8]
在生成页面的时候是否正常？
生成页面出现undefined materialcdn
配置文件是完整的吗？

**Comment by imzyf** [comment]
没有发现类似情况，可直接 push 这个项目，我进行下 hexo g

**Comment by tyl569** [comment]
原因：pull项目的时候需要做下面操作
> 为防止造成冲突，主题以 _config.template.yml 文件取代 _config.yml 文件，用以参考配置。 需要手动将 material 文件夹中的 _config.template.yml 复制一份并重命名为 _config.yml。

然后再仅需使用`hexo g`等命令

**Comment by imzyf** [comment]
_config.yml 应该是被作者 ignore 了，这个在使用中是不行。我们要统一配置文件，我会上传上 _config.yml

**Comment by imzyf** [comment]
@tyl569 我已经提交 先删除你的 _config.yml 重新来 pull 项目
